version: "3.9"
services:
  web:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db
      PORT: 5000
    ports:
      - "5000:5000"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/postgresql/data
volumes:
  db_volume: {}
